#  -------------------------------------------------- 
#  Generated by Enterprise Architect Version 7.5.844
#  Created On : quarta-feira, 14 abril, 2010 
#  DBMS       : MySql 
#  -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


# Drop Tables, Stored Procedures and Views 
DROP TABLE IF EXISTS `FacetObjects`;
DROP TABLE IF EXISTS `FacetTypes`;
DROP TABLE IF EXISTS `MediaData`;
DROP TABLE IF EXISTS `MediaFacetAssoc`;

# Create Tables 
CREATE TABLE `FacetObjects`
(
	`id` INTEGER NOT NULL,
	`facetTypeId` INTEGER NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`published` TINYINT NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`facetTypeId`)
) ;


CREATE TABLE `FacetTypes`
(
	`id` INTEGER NOT NULL,
	`title` VARCHAR(150) NOT NULL,
	`showAsColumn` INTEGER NOT NULL,
	`published` TINYINT NOT NULL,
	PRIMARY KEY (`id`)
) ;


CREATE TABLE `MediaData`
(
	`id` INTEGER NOT NULL,
	`filename` VARCHAR(255) NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`lenght` INTEGER NOT NULL,
	`added` TIMESTAMP NOT NULL,
	PRIMARY KEY (`id`)
) ;


CREATE TABLE `MediaFacetAssoc`
(
	`id` INTEGER NOT NULL,
	`mediaId` INTEGER NOT NULL,
	`facetObjectId` INTEGER NOT NULL,
	PRIMARY KEY (`id`),
	KEY (`facetObjectId`),
	KEY (`mediaId`)
) ;



SET FOREIGN_KEY_CHECKS=1;


# Create Foreign Key Constraints 
ALTER TABLE `FacetObjects` ADD CONSTRAINT `FK_FacetObjects_FacetTypes` 
	FOREIGN KEY (`facetTypeId`) REFERENCES `FacetTypes` (`id`)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `MediaFacetAssoc` ADD CONSTRAINT `FK_MediaFacetAssoc_FacetObjects` 
	FOREIGN KEY (`facetObjectId`) REFERENCES `FacetObjects` (`id`)
	ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `MediaFacetAssoc` ADD CONSTRAINT `FK_MediaFacetAssoc_MediaData` 
	FOREIGN KEY (`mediaId`) REFERENCES `MediaData` (`id`)
	ON DELETE CASCADE ON UPDATE CASCADE;
